sudo: required
services:
  - docker

before_install:
  - docker build -t mersock/simple-react-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mersock/simple-react-complex npm test

after_success:
  - docker build -t mersock/simple-react-complex-client ./client
  - docker build -t mersock/simple-react-complex-nginx ./nginx
  - docker build -t mersock/simple-react-complex-server ./server
  - docker build -t mersock/simple-react-complex-worker ./worker

  #login docker account
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image to docker hub
  - docker push mersock/simple-react-complex-client 
  - docker push mersock/simple-react-complex-nginx 
  - docker push mersock/simple-react-complex-server 
  - docker push mersock/simple-react-complex-worker 