sudo: required
services:
  - docker

before_install:
  - docker build -t mersock/simple-react-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mersock/simple-react-complex npm test

after_success:
  - docker build -t mersock/simple-react-complex-client ./client
  - docker build -t mersock/simple-react-complex-nginx ./nginx
  - docker build -t mersock/simple-react-complex-server ./server
  - docker build -t mersock/simple-react-complex-worker ./worker

  #login docker account
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image to docker hub
  - docker push mersock/simple-react-complex-client 
  - docker push mersock/simple-react-complex-nginx 
  - docker push mersock/simple-react-complex-server 
  - docker push mersock/simple-react-complex-worker 

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker 
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-799067542302
  bucket_path: docker-multi
  on:
    branch: master  

access_key_id:
  secure: $AWS_ACCESS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY